### ISSUE TITLE
Error in MAnage Access Areas: User may delete Access Area name but not edit it.

### ISSUE THREAD

**Issue by rjquek** [mcguffin/wp-access-areas#33]
Firstly excellent plugin I must say!

Was happily using it when I discovered that I cannot edit the access area name. Had assigned it to multiple users and posts and discovered that I cannot edit the name! Help!

Get the following error:
Warning: extract() expects parameter 1 to be array, null given in *******************wp-content/plugins/wp-access-areas/inc/class-wpaa_accessarea.php on line 213

Warning: Cannot modify header information - headers already sent by (output started at ****************_/wp-content/plugins/wp-access-areas/inc/class-wpaa_accessarea.php:213) in ***_*************/wp-includes/pluggable.php on line 1179

**Comment by mcguffin** [comment]
Ooops, my fault. 
Should be fixed in the latest commit (and also in the WP Plugin repository).
