### ISSUE TITLE
Restricted post accessible via Archive or Calendar

### ISSUE THREAD

**Issue by rjquek** [mcguffin/wp-access-areas#34]
Restriction works when the post is click on directly.

However, when the post is queried for via calendar or archive, it appears!

Security issue?

**Comment by mcguffin** [comment]
Calendar Widget: I already had this issue before, found it not fixable and finally put a note on the official readme: https://wordpress.org/plugins/wp-access-areas/ 
(There is a WP Core issue on that topic also: https://core.trac.wordpress.org/ticket/29319)

Archive: That one should have been fixed already. Which WP- and plugin versions are you using?
