### ISSUE TITLE
PHP notice due incorrect usage of is_singular()

### ISSUE THREAD

**Issue by Grezvany13** [mcguffin/wp-access-areas#35]
On both the front- and backend I get the following notice which got caused by wp-access-areas;

Obviously it doesn't break anything and visitors don't see it, however on our development locations it's showing and breaking other parts of the site due the messaging. And of course it creates a performance issue even while not showing the notice.

> ( ! ) Notice: is_singular was called <strong>incorrectly</strong>. Conditional query tags do not work before the query is run. Before then, they always return false. Please see <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 3.1.) in /vagrant/public/wp-includes/functions.php on line 3792

This is a part of the backtrace generated by XDebug:

> 12  0.5502  5781688 WP_Query->query( )  .../post.php:1646
> 13  0.5502  5791840 WP_Query->get_posts( )  .../query.php:4018
> 14  0.5553  6055512 apply_filters_ref_array( )  .../query.php:3197
> 15  0.5553  6057416 call_user_func_array:{/vagrant/public/wp-includes/plugin.php:291} ( )   .../plugin.php:291
> 16  0.5553  6057496 WPAA_Posts::get_posts_where( )  .../plugin.php:291
> 17  0.5553  6057640 WPAA_Posts::_get_where( )   .../class-wpaa_posts.php:281
> **18    0.5553  6057688 is_singular( )  .../class-wpaa_posts.php:302**
> 19  0.5554  6058176 _doing_it_wrong( )  .../query.php:634
> 20  0.5555  6059496 trigger_error ( )   .../functions.php:3792

Since I'm not familiar with the plugin itself, I won't be able to provide a possible fix.

Tested with plugin version 1.4.3 and 1.4.4
Tested with WP version 4.4.2

Using

```
define('WP_DEBUG', true);
error_reporting(-1);
ini_set('display_errors', true);
ini_set('display_startup_errors', true);
```

**Comment by mcguffin** [comment]
I couldn't reproduce the issue in my test install.
Anyway, I added a condition that (in theory) should eliminate the `_doing_it_wrong()` message. 
Could you be so kind and test it on your system?

**Comment by Grezvany13** [comment]
The fix works and doesn't trigger any errors/notices anymore.

Thank you for the quick response and fix!
