### ISSUE TITLE
Fatal error when updating post in wp admin

### ISSUE THREAD

**Issue by DavidTogg** [mcguffin/wp-access-areas#40]
Gives me this message when changing a post entry in wp admin (newest version of all running):

Fatal error: Uncaught ArgumentCountError: Too few arguments to function WPAA_EditPost::can_edit_edit_cap(), 0 passed in D:\xampp\htdocs\wp-content\plugins\wp-access-areas\inc\class-wpaa_editpost.php on line 141 and exactly 1 expected in D:\xampp\htdocs\wp-content\plugins\wp-access-areas\inc\class-wpaa_editpost.php:255 Stack trace: #0 D:\xampp\htdocs\wp-content\plugins\wp-access-areas\inc\class-wpaa_editpost.php(141): WPAA_EditPost::can_edit_edit_cap() #1 D:\xampp\htdocs\wp-includes\class-wp-hook.php(286): WPAA_EditPost::edit_post(Array, Array) #2 D:\xampp\htdocs\wp-includes\plugin.php(203): WP_Hook->apply_filters(Array, Array) #3 D:\xampp\htdocs\wp-includes\post.php(3357): apply_filters('wp_insert_post_...', Array, Array) #4 D:\xampp\htdocs\wp-includes\post.php(3654): wp_insert_post(Array, false) #5 D:\xampp\htdocs\wp-admin\includes\post.php(377): wp_update_post(Array) #6 D:\xampp\htdocs\wp-admin\post.php(194): edit_post() #7 {main} thrown in D:\xampp\htdocs\wp-content\plugins\wp-access-areas\inc\class-wpaa_editpost.php on line 255

**Comment by mcguffin** [comment]
Version 1.5.4 is out. Should be fixed.
