### ISSUE TITLE
WP Access Area Problems on my Site

### ISSUE THREAD

**Issue by Meletha** [mcguffin/wp-access-areas#41]
Using the WPAA plugin caused severe problems to my website. The following warning appeared on the top of the page: 
Warning
: Parameter 2 to WPAA_Posts::get_posts_where() expected to be a reference, value given in
/home/hopepu1/accountsapp.biz/wp-includes/class-wp-hook.php on line 286

I will like to use the plugin.  Kindly make corrections to this problem?  Thank you.

**Comment by mcguffin** [comment]
Just released v1.5.5.
(It was already fixed in commit 1e56a78059590b1cdc18235ee61c2236d6471b90, but not published on wp org.)
