### ISSUE TITLE
Redirection to wrong page after user creation

### ISSUE THREAD

**Issue by mtrineyev** [mcguffin/wp-access-areas#43]
Hello,

after adding new user appears page with WP err message "The link you followed has expired".

In fine user is normally created, admin has recieved e-mail about creation of new user, but new user itself hasn't recieve any information message.

If I switch off wp-access-areas plagin everything working without errors.

**Comment by mcguffin** [comment]
Hi,
I just tried this with a default WordPress and latest WP Access Areas plugin – it worked as it should.
Maybe there is another plugin, that does something with the user-management too? Would you mind to take a look?
